pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Checkout code from a version control system
                echo 'Checking out code...'
                // For example, using Git
                git 'https://github.com/n1603/proda-repo.git'
            }
        }

        stage('Build') {
            steps {
                echo 'Building the application...'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests...'
            }
        }

        stage('Deploy') {
            steps {
                echo 'Deploying the application...'
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed!'
        }
    }
}

